### ISSUE TITLE
Failed to install any app on Linux

### ISSUE THREAD

**Issue by Lerentis** [quanglam2807/appifier#168]
Hey there. i was trying to install Google Play Books, but it always failes. 
Toggling developer tools just gives me this:
```
actions.js:36
Error: Installing failed.
    at EventEmitter.o (install-app-async.js:19)
    at emitThree (events.js:140)
    at EventEmitter.emit (events.js:216)
```
is this a known problem? Can i provide more logs here? love the idea of this application (:

EDIT: I can't install any app in fact. just tested against master with yarn electron-dev running.

uname -a
Linux 4.13.8-1-ARCH x86_64
electron -v
v1.6.15
Installed via AppImage

**Comment by bayang** [comment]
same here, Linux 4.10 x86_64 with Appimage

**Comment by quanglam2807** [comment]
@bayang I'm working on it.

**Comment by quanglam2807** [comment]
Can you guys test the new version? For a reason, WebCatalog didn't work correctly with the `AppImage` format so you need to install it again with `.deb`, `.rpm` or `.pacman` file.

https://github.com/webcatalog/webcatalog/releases/tag/v7.3.0

**Comment by bayang** [comment]
still no luck here on ubuntu 17.04 with the .deb
![webcatalog](https://user-images.githubusercontent.com/11558944/32160756-6aa5a316-bd53-11e7-91c1-d0d1de2fb198.png)

**Comment by Lerentis** [comment]
Same on Arch with the .pacman :/

**Comment by Mgldvd** [comment]
v7.3.0 fail on Linux mint 18.2 with .deb
![image](https://user-images.githubusercontent.com/2009698/32175837-13834060-bd54-11e7-9286-fc369601a83c.png)

**Comment by damigarcia** [comment]
Same problem with 7.3.0 in a CentOs 7.3.1611 installed with WebCatalog-7.3.0.x86_64.rpm.

**Comment by Mofiqul** [comment]
Same problem with 7.3.0 in Ubuntu 16.04 64bit. installed from .deb

**Comment by quanglam2807** [comment]
I've found the problem. It'll be fixed soon.

**Comment by quanglam2807** [comment]
It should be fixed in v7.3.2 https://github.com/webcatalog/webcatalog/releases/tag/v7.3.2

**Comment by damigarcia** [comment]
I'm still having the problem.
I have CentOs 7.3.1611 installed with WebCatalog-7.3.2.x86_64.rpm.
I've uninstalled and then install it.
How can I help you? is there any log I can take a look?
![selection_517](https://user-images.githubusercontent.com/98479/32342065-16b1dfa8-bfde-11e7-8fa9-ce61bb94c862.png)
![selection_518](https://user-images.githubusercontent.com/98479/32342094-2a5f6e30-bfde-11e7-810b-f1a7d466e6d0.png)
The console log shows:

Error: Installing failed.
    at EventEmitter.o (install-app-async.js:19)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)

**Comment by quanglam2807** [comment]
Let's move to #221
