### ISSUE TITLE
 Ability to install apps using separate file

### ISSUE THREAD

**Issue by matrixik** [quanglam2807/appifier#180]
Would be nice to have ability to install apps from separate file instead of connecting to a server. 

Problem: I am able to install apps on Linux but on Windows I can't any (probably because of corporate proxy)
```
WebCatalog: Version 7.4.2
electron: 1.7.9
chrome: 58.0.3029.110
v8: 5.8.283.38
node: 7.9.0
```

```
Error: connect ETIMEDOUT 104.18.33.220:443
    at ChildProcess.child.on (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\build\libs\install-app-async\index.js:51:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
actions.js:40 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:19)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```

Other way around this would be to have Webcatalog app as portable instead of installer on Windows so I could install necessary apps on one computer and use it on all other computers without need for many downloads of same app.

One more thing:
when going to https://104.18.33.220/ in Firefox I can see error: `SSL_ERROR_NO_CYPHER_OVERLAP`.

**Comment by quanglam2807** [comment]
If somebody can turn this one into a CLI, it would be possible. https://github.com/webcatalog/molecule 

I'm quite busy to work on this.

**Comment by quanglam2807** [comment]
Resolved with #113 #212

**Comment by matrixik** [comment]
Hmm, thank you for looking into this but I still can't install any page:
When creating custom app:
```
Error: connect ETIMEDOUT 192.30.253.113:443
    at ChildProcess.child.on (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\build\libs\install-app-async\index.js:47:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
When downloading from server:
```
Error: Forked script error
    at ChildProcess.child.on (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\build\libs\install-app-async\index.js:56:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
actions.js:47 Error: Installing failed.
    at EventEmitter.o (install-app-async.js:23)
    at emitThree (events.js:121)
    at EventEmitter.emit (events.js:197)
```
Debug info:
```
WebCatalog
Version 8.0.3
electron: 1.7.9
chrome: 58.0.3029.110
v8: 5.8.283.38
node: 7.9.0
```
Hmmm, maybe webcatalog is not getting system proxy on Windows 8.1?

**Comment by quanglam2807** [comment]
Can you try to create a custom app with a local PNG?

**Comment by matrixik** [comment]
Thank you for idea.

Tried it and still have same error:
```
Error: connect ETIMEDOUT 192.30.253.112:443
    at ChildProcess.child.on (C:\Users\ZybortD\AppData\Local\Programs\WebCatalog\resources\app\build\libs\install-app-async\index.js:47:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Looks like 192.30.253.112 is pointing to github, no idea what could be the problem, I'm writing now from the same machine that I try to install custom app. Could I somehow debug it more for you?

**Comment by matrixik** [comment]
Hmm, the problem could be with the way how it's connecting to the github server. For doing `git clone` I needed to add http configuration to global `.gitconfig`.

**Comment by quanglam2807** [comment]
@matrixik The app doesn't log the bug in the forked script so it's quite tricky to debug. I need to look at this. It sends and logs the error message but it doesn't log the line number.

https://github.com/webcatalog/webcatalog/blob/master/public/libs/install-app-async/script.js#L153

I need to work on an update.

**Comment by quanglam2807** [comment]
Let's move to #221

**Comment by matrixik** [comment]
Thank you for looking into it.
